
_DF_ = "/"
JSON_STRUCTURE_FILE_NAME = "postStructure.json"

INSTALL_PATH = "/opt/rave"
TOKEN_FILE = INSTALL_PATH + _DF_ + ".token"
JSON_STRUCTURE_FILE_PATH = INSTALL_PATH + _DF_ + JSON_STRUCTURE_FILE_NAME
WEB_HOOK_URL = "https://rave-osioluyp-test.herokuapp.com/717635382:AAE9Qy-9Vd0wAsUAVnII9y9CLE-8E-s9EAA"

TEMP_HOST_FILE = INSTALL_PATH + _DF_ + ".temphost"